name: stacks-starterrrr
description: This is a stack to create a stack.
branding:
  icon: layers
  color: blue

inputs:
  - name: Isyourstackgonnarock
    default: true
    type: boolean
    description: Currently, there is a limitation that stacks need at least one input. It's getting removed soon. The response here does not really matter but I have a hunch it's true.

config:
  repo-metadata:
    parameters:
      topics:
      - rails
      - sql

