name: stacks-starterrrr
description: This is a stack to create a stack.
branding:
  icon: layers
  color: blue

inputs:
  - name: abc

configs:
  repo-metadata:
    parameters:
      topics:
      - rails
      - sql

